apiVersion: apps/v1
kind: Deployment
metadata:
  name: pidonos
  labels:
    app: pidonos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pidonos
  template:
    metadata:
      labels:
        app: pidonos
    spec:
      containers:
      - name: pidonos
        image: ghcr.io/REPLACE_OWNER/pidonos:REPLACE_IMAGE_SHA
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"
